packages:
  - "packages/algebrite"
  - "packages/atoms"
  - "packages/context"
  - "packages/cs-parse"
  - "packages/diagnostics"
  - "packages/directive"
  - "packages/e2e"
  - "packages/eigenmath"
  - "packages/em-parse"
  - "packages/engine"
  - "packages/hashing"
  - "packages/helpers"
  - "packages/hilbert"
  - "packages/js-parse"
  - "packages/mint"
  - "packages/native"
  - "packages/py-parse"
  - "packages/stack"
  - "packages/stepper"
  - "packages/tree"
  - "packages/units"
